--- 
language: scala

install:
  - |
    # From: https://eed3si9n.com/sbt-1.4.9
    # Remove this when https://github.com/travis-ci/travis-build/pull/1980 is fixed
    export SBT_LAUNCHER=1.4.9
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt

script: >
 sbt ++$TRAVIS_SCALA_VERSION check mdoc coverage $PROJECT/test coverageReport &&
 cd target &&
 git clone https://github.com/lemonlabsuk/scala-uri-demo.git &&
 cd scala-uri-demo &&
 sbt -Dscala.ver=$TRAVIS_SCALA_VERSION -Dscala.uri.ver=3.3.0 test &&
 cd "$TRAVIS_BUILD_DIR"

jdk:
  - openjdk8

jobs:
  include:
    - scala: [2.13.6]
      env: PROJECT=scalaUriJVM
    - scala: [2.13.6]
      env: PROJECT=scalaUriJS
    - scala: [2.12.13]
      env: PROJECT=scalaUriJVM
    - scala: [2.12.13]
      env: PROJECT=scalaUriJS

before_script:
  - nvm install 10 # nodejs < 10 fails finding URL class

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
