--- 
language: scala
script: >
 sbt $COVERAGE ++$TRAVIS_SCALA_VERSION check mdoc coverage $PROJECT/test coverageReport &&
 cd target &&
 git clone https://github.com/lemonlabsuk/scala-uri-demo.git &&
 cd scala-uri-demo &&
 sbt -Dscala.ver=$TRAVIS_SCALA_VERSION -Dscala.uri.ver=2.2.4 test &&
 cd "$TRAVIS_BUILD_DIR"

jdk:
  - openjdk8

jobs:
  include:
    - scala: [2.13.2]
      env: PROJECT=scalaUriJVM COVERAGE=coverageOff
    - scala: [2.13.2]
      env: PROJECT=scalaUriJS COVERAGE=coverageOff
    - scala: [2.12.11]
      env: PROJECT=scalaUriJVM COVERAGE=coverageOn
    - scala: [2.12.11]
      env: PROJECT=scalaUriJS COVERAGE=coverageOff

before_script:
  - nvm install 10 # nodejs < 10 fails finding URL class

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
