name: scala-uri CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [2.12.17, 2.13.8]
        project: [scalaUriJVM, scalaUriJS]
        coverage: [coverage]
        coverageReport: [coverageReport]
        include:
          # https://github.com/scoverage/scalac-scoverage-plugin/issues/299
          - scala: 3.1.3
            project: scalaUriJVM
            coverage: ""
            coverageReport: ""
          - scala: 3.1.3
            project: scalaUriJS
            coverage: ""
            coverageReport: ""

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          key: scala-dependencies
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14' # nodejs < 10 fails finding URL class

      - name: Run tests
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          PROJECT: ${{ matrix.project }}
          COVERAGE: ${{ matrix.coverage }}
          COVERAGE_REPORT: ${{ matrix.coverageReport }}
          SBT_OPTS: -Xss10m
        run: >
          sbt ++$SCALA_VERSION check mdoc $COVERAGE $PROJECT/test $COVERAGE_REPORT &&
          cd target &&
          git clone https://github.com/lemonlabsuk/scala-uri-demo.git &&
          cd scala-uri-demo &&
          sbt -Dscala.ver=$SCALA_VERSION -Dscala.uri.ver=4.0.2 test &&
          cd "$TRAVIS_BUILD_DIR"

      - name: Report to CodeCov
        run: bash <(curl -s https://codecov.io/bash)
